let token = sessionStorage.getItem("kloksieAdminToken") || "";
let products = [];
let orders = [];
let draftImages = [];
const loginPanel = document.getElementById("loginPanel"), dashboard = document.getElementById("dashboard"), loginMessage = document.getElementById("loginMessage"), dashboardMessage = document.getElementById("dashboardMessage"), form = document.getElementById("productForm"), productList = document.getElementById("productList");
function escapeHtml(value = "") { return String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
function showMessage(el, message, success = false) { el.textContent = message || ""; el.classList.toggle("success", Boolean(success)); }
function headers() { return { "Content-Type":"application/json", Authorization:`Bearer ${token}` }; }
async function request(url, options={}) { const response = await fetch(url, options), data = await response.json().catch(() => ({})); if (response.status === 401) signOut(); if (!response.ok) throw new Error(data.error || "Something went wrong."); return data; }
function newProduct() { form.reset(); form.elements.active.value="true"; form.elements.sort_order.value="0"; form.elements.id.value=""; draftImages=[]; document.getElementById("variantsList").innerHTML=""; renderImages(); document.getElementById("formTitle").textContent="Add a product"; document.getElementById("resetForm").hidden=true; }
function productValues(product) { for (const [key,value] of Object.entries(product)) { const field=form.elements.namedItem(key); if (!field) continue; if(field.type==="checkbox") field.checked=Boolean(value); else if (key!=="images" && key!=="variants") field.value=value ?? ""; } }
function editProduct(id) { const product=products.find(p=>p.id===id); if(!product)return; productValues(product); draftImages=(product.images||[]).map((img,i)=>({image_url:img.image_url,sort_order:i,is_featured:Boolean(img.is_featured)})); renderImages(); renderVariants(product.variants||[]); document.getElementById("formTitle").textContent="Edit product"; document.getElementById("resetForm").hidden=false; window.scrollTo({top:0,behavior:"smooth"}); }
function renderImages(){ const el=document.getElementById("imagePreview"); el.innerHTML=draftImages.map((img,i)=>`<div class="image-preview ${img.is_featured?"featured":""}" data-feature="${i}"><img src="${escapeHtml(img.image_url)}" alt=""><span class="featured-label">${img.is_featured?"FEATURED":"SET AS FEATURED"}</span><button type="button" class="remove-image" data-remove-image="${i}">×</button></div>`).join(""); }
function renderVariants(variants=[]){ const el=document.getElementById("variantsList"); el.innerHTML=""; variants.forEach(addVariantRow); }
function addVariantRow(variant={color:"",size:"",stock:0}){ const row=document.createElement("div"); row.className="variant-row"; row.innerHTML=`<input class="variant-color" placeholder="Color" value="${escapeHtml(variant.color)}"><input class="variant-size" placeholder="Size" value="${escapeHtml(variant.size)}"><input class="variant-stock" type="number" min="0" placeholder="Stock" value="${Number(variant.stock)||0}"><button type="button" class="remove-variant">×</button>`; document.getElementById("variantsList").appendChild(row); }
async function uploadFiles(files){ if(!files.length)return; const payload=[]; for(const file of files){ if(file.size>8*1024*1024) throw new Error(`${file.name} is larger than 8MB.`); payload.push(await new Promise((resolve,reject)=>{const reader=new FileReader(); reader.onload=()=>resolve({name:file.name,data:reader.result}); reader.onerror=reject; reader.readAsDataURL(file);})); } const data=await request("/api/admin/upload-images",{method:"POST",headers:headers(),body:JSON.stringify({files:payload})}); (data.images||[]).forEach((img,i)=>draftImages.push({image_url:img.image_url,sort_order:draftImages.length+i,is_featured:draftImages.length===0&&i===0})); if(!draftImages.some(x=>x.is_featured)&&draftImages[0])draftImages[0].is_featured=true; renderImages(); }
function collectVariants(){ return [...document.querySelectorAll("#variantsList .variant-row")].map(row=>({color:row.querySelector(".variant-color").value.trim(),size:row.querySelector(".variant-size").value.trim(),stock:Number(row.querySelector(".variant-stock").value)})).filter(v=>v.color||v.size); }
function renderProducts(){ document.getElementById("inventoryCount").textContent=`${products.length} ${products.length===1?"ITEM":"ITEMS"}`; if(!products.length){productList.innerHTML='<p class="empty">No products yet.</p>';return;} productList.innerHTML=products.map(p=>`<article class="inventory-row"><img src="${escapeHtml(p.image||p.images?.[0]?.image_url||"assets/product-01.jpg")}" alt=""><div><h3>${escapeHtml(p.name)}</h3><p>₱${Number(p.price||0).toLocaleString("en-PH")} · ${Number(p.stock||0)} base stock</p><p class="meta">${escapeHtml(p.category||"Archive")}${p.variants?.length?` · ${p.variants.length} VARIANTS`:""}${p.images?.length?` · ${p.images.length} IMAGES`:""}${p.active?"":" · HIDDEN"}</p></div><div class="row-actions"><button data-edit="${escapeHtml(p.id)}">EDIT</button><button data-hide="${escapeHtml(p.id)}">${p.active?"HIDE":"SHOW"}</button></div></article>`).join(""); }
async function loadProducts(){ const data=await request("/api/admin/products",{headers:headers()}); products=data.products||[]; renderProducts(); }
function formatDate(value){const d=new Date(value);return Number.isNaN(d.getTime())?"":d.toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"});}
function renderOrders(){const el=document.getElementById("ordersList");if(!orders.length){el.innerHTML='<p class="orders-empty">No orders yet.</p>';return;}el.innerHTML=orders.map(o=>{const items=Array.isArray(o.items)?o.items:[];const itemHtml=items.map(i=>`<div class="order-item"><span>${escapeHtml(i.name||"Item")} × ${Number(i.quantity||0)}${[i.color,i.size].filter(Boolean).length?` — ${escapeHtml([i.color,i.size].filter(Boolean).join(" / "))}`:""}</span><strong>₱${(Number(i.price||0)*Number(i.quantity||0)).toLocaleString("en-PH")}</strong></div>`).join("");return `<article class="order-row" data-order-row="${escapeHtml(o.id)}"><div class="order-summary"><div><h3>${escapeHtml(o.reference)}</h3><p>${escapeHtml(o.customer_name||"Customer")} · ${escapeHtml(o.customer_email||"")}</p></div><div><p>${formatDate(o.created_at)}</p><p>₱${Number(o.total_php||0).toLocaleString("en-PH")}</p></div><div><span class="order-status">${escapeHtml(String(o.status||"pending").toUpperCase())}</span></div><div><p>${escapeHtml(o.customer_phone||"")}</p></div><button class="order-view" data-order-view="${escapeHtml(o.id)}">VIEW</button></div><div class="order-details"><div class="order-details-grid"><div><strong>CUSTOMER</strong><p>${escapeHtml(o.customer_name||"")}<br>${escapeHtml(o.customer_email||"")}<br>${escapeHtml(o.customer_phone||"")}</p></div><div><strong>SHIPPING ADDRESS</strong><p>${escapeHtml(o.shipping_address||"Not provided")}</p></div><div><strong>TOTAL</strong><p>₱${Number(o.total_php||0).toLocaleString("en-PH")}</p></div><div><strong>PAYMONGO SESSION</strong><p class="order-reference">${escapeHtml(o.paymongo_checkout_session_id||"Not available")}</p></div></div><div class="order-items"><strong>ITEMS</strong>${itemHtml||"<p>No item details.</p>"}</div><div style="margin-top:15px;display:flex;gap:10px;align-items:center;flex-wrap:wrap"><label><strong>ORDER STATUS</strong> <select class="order-status-select" data-order-status="${escapeHtml(o.id)}"><option value="pending" ${o.status==="pending"?"selected":""}>Pending</option><option value="paid" ${o.status==="paid"?"selected":""}>Paid</option><option value="processing" ${o.status==="processing"?"selected":""}>Processing</option><option value="shipped" ${o.status==="shipped"?"selected":""}>Shipped</option><option value="completed" ${o.status==="completed"?"selected":""}>Completed</option><option value="cancelled" ${o.status==="cancelled"?"selected":""}>Cancelled</option><option value="failed" ${o.status==="failed"?"selected":""}>Failed</option></select></label><button class="order-view" data-save-order="${escapeHtml(o.id)}">UPDATE STATUS</button></div></div></article>`;}).join("");}
async function loadOrders(){const data=await request("/api/admin/orders",{headers:headers()});orders=data.orders||[];renderOrders();}
async function openDashboard(){loginPanel.hidden=true;dashboard.hidden=false;try{await Promise.all([loadProducts(),loadOrders()]);}catch(e){showMessage(dashboardMessage,e.message);}}
function signOut(){token="";sessionStorage.removeItem("kloksieAdminToken");dashboard.hidden=true;loginPanel.hidden=false;newProduct();}
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();const b=e.currentTarget.querySelector("button");b.disabled=true;try{const password=new FormData(e.currentTarget).get("password"),data=await request("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});token=data.token;sessionStorage.setItem("kloksieAdminToken",token);e.currentTarget.reset();await openDashboard();}catch(err){showMessage(loginMessage,err.message);}finally{b.disabled=false;}});
document.getElementById("imageFiles").addEventListener("change",async e=>{try{await uploadFiles([...e.target.files]);e.target.value="";showMessage(dashboardMessage,"Images uploaded.",true);}catch(err){showMessage(dashboardMessage,err.message);}});
document.getElementById("imagePreview").addEventListener("click",e=>{const remove=e.target.closest("[data-remove-image]");if(remove){draftImages.splice(Number(remove.dataset.removeImage),1);if(draftImages.length&&!draftImages.some(x=>x.is_featured))draftImages[0].is_featured=true;return renderImages();}const card=e.target.closest("[data-feature]");if(card){draftImages.forEach((img,i)=>img.is_featured=i===Number(card.dataset.feature));draftImages.forEach((img,i)=>img.sort_order=i);renderImages();}});
document.getElementById("addVariant").addEventListener("click",()=>addVariantRow());
document.getElementById("variantsList").addEventListener("click",e=>{const b=e.target.closest(".remove-variant");if(b)b.parentElement.remove();});
form.addEventListener("submit",async e=>{e.preventDefault();if(!draftImages.length)return showMessage(dashboardMessage,"Please upload at least one product image.");const variants=collectVariants(), data=Object.fromEntries(new FormData(form));data.active=form.elements.active.value==="true";data.price=Number(data.price);data.stock=Number(data.stock);data.sort_order=Number(data.sort_order);data.images=draftImages.map((img,i)=>({...img,sort_order:i}));data.variants=variants;const editing=Boolean(data.id),button=form.querySelector(".save-product");button.disabled=true;showMessage(dashboardMessage,"");try{await request("/api/admin/products",{method:editing?"PUT":"POST",headers:headers(),body:JSON.stringify(data)});newProduct();showMessage(dashboardMessage,editing?"Product updated.":"Product added.",true);await loadProducts();}catch(err){showMessage(dashboardMessage,err.message);}finally{button.disabled=false;}});
productList.addEventListener("click",async e=>{const edit=e.target.closest("[data-edit]");if(edit)return editProduct(edit.dataset.edit);const hide=e.target.closest("[data-hide]");if(!hide)return;const p=products.find(x=>x.id===hide.dataset.hide);if(!p)return;try{await request("/api/admin/products",{method:"PUT",headers:headers(),body:JSON.stringify({...p,images:p.images||[],variants:p.variants||[],active:!p.active})});await loadProducts();showMessage(dashboardMessage,p.active?"Product hidden.":"Product is visible.",true);}catch(err){showMessage(dashboardMessage,err.message);}});
document.getElementById("ordersList").addEventListener("click",async e=>{const view=e.target.closest("[data-order-view]");if(view){const row=view.closest(".order-row");row.classList.toggle("open");return;}const save=e.target.closest("[data-save-order]");if(!save)return;const id=save.dataset.saveOrder,row=save.closest(".order-row"),select=row.querySelector(`[data-order-status="${CSS.escape(id)}"]`);if(!select)return;save.disabled=true;try{await request("/api/admin/orders",{method:"PATCH",headers:headers(),body:JSON.stringify({id,status:select.value})});await loadOrders();}catch(err){showMessage(document.getElementById("ordersMessage"),err.message);}finally{save.disabled=false;}});
document.getElementById("refreshOrders").addEventListener("click",async()=>{try{await loadOrders();showMessage(document.getElementById("ordersMessage"),"Orders refreshed.",true);}catch(err){showMessage(document.getElementById("ordersMessage"),err.message);}});
document.getElementById("resetForm").addEventListener("click",newProduct);document.getElementById("signOut").addEventListener("click",signOut);if(token)openDashboard();else newProduct();
