const FALLBACK_PRODUCTS=[];
let products=FALLBACK_PRODUCTS,activeCategory="All",currency=localStorage.getItem("kloksieCurrency")||"PHP",cart=JSON.parse(localStorage.getItem("kloksieCart")||"[]"),detailProduct=null,detailQuantity=1,detailSelections={};
const money=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}),usdMoney=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2});
const $=id=>document.getElementById(id),cartDrawer=$("cartDrawer"),cartItems=$("cartItems"),cartCount=$("cartCount"),cartTotal=$("cartTotal"),productModal=$("productModal");
function escapeHtml(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function safeImage(v){const x=String(v||"").trim();return /^(https?:\/\/|\/|assets\/)/i.test(x)?x:"assets/kloksie-logo.png";}
function currentPrice(p){return currency==="USD"?Number(p.international_price_usd||0):Number(p.price||0)}
function priceLabel(p){const n=currentPrice(p);return n>0?(currency==="USD"?usdMoney.format(n):money.format(n)):"PRICE TBD";}
function getProduct(id){return products.find(p=>p.id===id);}
function productImages(p){const imgs=Array.isArray(p.images)&&p.images.length?p.images:[];if(!imgs.length&&p.image)imgs.push({image_url:p.image,is_featured:true,sort_order:0});return imgs.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));}
function variants(p){return Array.isArray(p.variants)?p.variants:[];}
function saveCart(){localStorage.setItem("kloksieCart",JSON.stringify(cart));renderCart();}
function productCard(p){const unavailable=!currentPrice(p)||Number(p.stock)<1;const label=!currentPrice(p)?"PRICE TBD":Number(p.stock)<1?"SOLD OUT":"VIEW PIECE";const sub=[p.description,p.size?`SIZE ${p.size}`:""].filter(Boolean).join(" · ");return `<article class="product-card" data-product="${escapeHtml(p.id)}"><div class="product-image-wrap">${p.tag?`<span class="product-tag">${escapeHtml(p.tag)}</span>`:""}<img src="${escapeHtml(safeImage(p.image||productImages(p)[0]?.image_url))}" alt="${escapeHtml(p.alt||p.name)}" class="product-image" loading="lazy"><button class="quick-add" data-view="${escapeHtml(p.id)}" ${unavailable?"disabled":""}>${label}</button></div><div class="product-info"><div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(sub||p.category||"KLOKSIE SELECTED")}</p></div><strong>${priceLabel(p)}</strong></div></article>`;}
function renderCurrency(){document.querySelectorAll("[data-currency]").forEach(b=>b.classList.toggle("active",b.dataset.currency===currency));}
function setCurrency(c){currency=c;localStorage.setItem("kloksieCurrency",currency);renderCurrency();renderProducts();renderCart();if(detailProduct){$("detailPrice").textContent=priceLabel(detailProduct);updateDetailStock();}}
function renderFilters(){const fixed=["All","Shoes","Shirts","Accessories","Pants","Shorts","Long Sleeve","Jackets"];const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];const list=[...new Set([...fixed,...cats])];$("categoryFilters").innerHTML=list.map(c=>`<button class="filter-button ${c===activeCategory?"is-active":""}" data-filter="${escapeHtml(c)}">${escapeHtml(c).toUpperCase()}</button>`).join("");}
function renderProducts(){const selected=activeCategory==="All"?products:products.filter(p=>String(p.category||"").toLowerCase()===activeCategory.toLowerCase());$("productGrid").innerHTML=selected.map(productCard).join("");$("emptyProducts").hidden=Boolean(selected.length);$("productCount").textContent=`${selected.length} ${selected.length===1?"PIECE":"PIECES"}`;const featured=products.filter(p=>p.tag==="NEW"||p.tag==="NEW DROP").slice(0,2);$("featuredProducts").innerHTML=(featured.length?featured:products.slice(0,2)).map(productCard).join("");renderCurrency();}
function setCategory(c){activeCategory=c;renderFilters();renderProducts();$("shop").scrollIntoView({behavior:"smooth",block:"start"});}
function openProduct(id){const p=getProduct(id);if(!p)return;detailProduct=p;detailQuantity=1;detailSelections={};const imgs=productImages(p);$("detailMainImage").src=safeImage(imgs[0]?.image_url||p.image);$("detailMainImage").alt=p.alt||p.name;$("detailThumbnails").innerHTML=imgs.map((img,i)=>`<button class="detail-thumb ${i===0?"active":""}" data-image-index="${i}"><img src="${escapeHtml(safeImage(img.image_url))}" alt=""></button>`).join("");$("detailTag").textContent=p.tag||"";$("productDetailName").textContent=p.name;$("detailPrice").textContent=priceLabel(p);$("detailDescription").textContent=p.description||"";$("detailQuantity").textContent="1";renderDetailOptions();updateDetailStock();productModal.classList.add("open");productModal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";}
function closeProduct(){productModal.classList.remove("open");productModal.setAttribute("aria-hidden","true");document.body.style.overflow="";detailProduct=null;}
function renderDetailOptions(){const p=detailProduct,vs=variants(p),colors=[...new Set(vs.map(v=>v.color).filter(Boolean))],sizes=[...new Set(vs.map(v=>v.size).filter(Boolean))],html=[];if(colors.length)html.push(`<div class="detail-option"><span>COLOR</span><div class="option-list">${colors.map(v=>`<button class="option-button ${detailSelections.color===v?"selected":""}" data-option="color" data-value="${escapeHtml(v)}">${escapeHtml(v)}</button>`).join("")}</div></div>`);if(sizes.length)html.push(`<div class="detail-option"><span>SIZE</span><div class="option-list">${sizes.map(v=>`<button class="option-button ${detailSelections.size===v?"selected":""}" data-option="size" data-value="${escapeHtml(v)}">${escapeHtml(v)}</button>`).join("")}</div></div>`);$("detailOptions").innerHTML=html.join("");}
function selectedVariant(){if(!detailProduct)return null;const vs=variants(detailProduct),colors=[...new Set(vs.map(v=>v.color).filter(Boolean))],sizes=[...new Set(vs.map(v=>v.size).filter(Boolean))];if(!vs.length)return null;if(colors.length&&!detailSelections.color)return null;if(sizes.length&&!detailSelections.size)return null;return vs.find(v=>(!colors.length||v.color===detailSelections.color)&&(!sizes.length||v.size===detailSelections.size))||null;}
function updateDetailStock(){if(!detailProduct)return;const v=selectedVariant(),required=variants(detailProduct).length>0,stock=v?v.stock:detailProduct.stock;$("detailStock").textContent=required&&!v?"SELECT COLOR AND SIZE":stock>0?`${stock} IN STOCK`:"SOLD OUT";$("detailAdd").disabled=Number(stock)<1||(!v&&required)||!currentPrice(detailProduct);}
function addSelectedToCart(){const p=detailProduct;if(!p||!currentPrice(p))return alert(`This item does not have a ${currency==="USD"?"international USD":"PH"} price yet.`);const v=selectedVariant(),hasVars=variants(p).length>0;if(hasVars&&!v)return alert("Please select the available color and size before adding to your bag.");const stock=v?v.stock:p.stock;if(stock<detailQuantity)return alert("Only the available stock can be added.");const key=`${p.id}::${v?.color||""}::${v?.size||""}`;const existing=cart.find(i=>i.key===key);if(existing){if(existing.quantity+detailQuantity>stock)return alert("Only the available stock can be added.");existing.quantity+=detailQuantity;}else cart.push({key,id:p.id,color:v?.color||"",size:v?.size||"",quantity:detailQuantity});saveCart();closeProduct();openCart();}
function changeQuantity(id,key,diff){const item=cart.find(i=>(i.key===key||(!i.key&&i.id===id)));const p=getProduct(id);if(!item||!p)return;const v=variants(p).find(x=>(x.color||"")===(item.color||"")&&(x.size||"")===(item.size||"")),stock=v?v.stock:p.stock;item.quantity+=diff;if(item.quantity<1)cart=cart.filter(x=>x!==item);if(item.quantity>stock){item.quantity=stock;alert("Only the available stock can be added.");}saveCart();}
function renderCart(){cart=cart.filter(i=>getProduct(i.id)&&getProduct(i.id).active!==false);cartCount.textContent=cart.reduce((s,i)=>s+i.quantity,0);if(!cart.length){cartItems.innerHTML='<p class="empty-cart">Your bag is empty.</p>';cartTotal.textContent=currency==="USD"?"$0.00":"₱0";localStorage.setItem("kloksieCart",JSON.stringify(cart));return;}cartItems.innerHTML=cart.map(i=>{const p=getProduct(i.id);const detail=[i.color,i.size].filter(Boolean).join(" / ");return `<div class="cart-row"><img src="${escapeHtml(safeImage(p.image||productImages(p)[0]?.image_url))}" alt="${escapeHtml(p.name)}"><div><h3>${escapeHtml(p.name)}</h3><p>${priceLabel(p)}${detail?` · ${escapeHtml(detail)}`:""}</p><div class="quantity-controls"><button data-quantity="-1" data-id="${escapeHtml(p.id)}" data-key="${escapeHtml(i.key||p.id)}">−</button><span>${i.quantity}</span><button data-quantity="1" data-id="${escapeHtml(p.id)}" data-key="${escapeHtml(i.key||p.id)}">+</button></div></div><button class="remove-item" data-remove="${escapeHtml(i.key||p.id)}">REMOVE</button></div>`;}).join("");cartTotal.textContent=(currency==="USD"?usdMoney:money).format(cart.reduce((s,i)=>s+currentPrice(getProduct(i.id))*i.quantity,0));localStorage.setItem("kloksieCart",JSON.stringify(cart));}
function openCart(){cartDrawer.classList.add("open");cartDrawer.setAttribute("aria-hidden","false");}function closeCart(){cartDrawer.classList.remove("open");cartDrawer.setAttribute("aria-hidden","true");}
async function loadProducts(){try{const r=await fetch("/api/products",{headers:{Accept:"application/json"}}),d=await r.json();if(r.ok&&Array.isArray(d.products))products=d.products;}catch(e){console.warn("Catalog load failed",e);}renderFilters();renderProducts();renderCart();}
document.addEventListener("click",e=>{const cur=e.target.closest("[data-currency]");if(cur)return setCurrency(cur.dataset.currency);const view=e.target.closest("[data-view],.product-card");if(view&&!e.target.closest("button[data-filter]")){const id=view.dataset.view||view.dataset.product;if(id)return openProduct(id);}const filter=e.target.closest("[data-filter], [data-category]");if(filter)return setCategory(filter.dataset.filter||filter.dataset.category);const thumb=e.target.closest("[data-image-index]");if(thumb&&detailProduct){const img=productImages(detailProduct)[Number(thumb.dataset.imageIndex)];if(img){$("detailMainImage").src=safeImage(img.image_url);document.querySelectorAll(".detail-thumb").forEach(x=>x.classList.remove("active"));thumb.classList.add("active");}return;}const opt=e.target.closest("[data-option]");if(opt){detailSelections[opt.dataset.option]=opt.dataset.value;renderDetailOptions();updateDetailStock();return;}const remove=e.target.closest("[data-remove]");if(remove){cart=cart.filter(i=>(i.key||i.id)!==remove.dataset.remove);return saveCart();}const q=e.target.closest("[data-quantity]");if(q)return changeQuantity(q.dataset.id,q.dataset.key,Number(q.dataset.quantity));if(e.target.closest("[data-close-product]"))closeProduct();});
$("openCart").addEventListener("click",openCart);$("closeCart").addEventListener("click",closeCart);$("closeCartBtn").addEventListener("click",closeCart);$("openMenu").addEventListener("click",()=>{const m=$("mobileNav"),open=m.hidden;m.hidden=!open;$("openMenu").setAttribute("aria-expanded",String(open));});$("mobileNav").addEventListener("click",()=>{$("mobileNav").hidden=true;$("openMenu").setAttribute("aria-expanded","false");});
$("detailMinus").addEventListener("click",()=>{detailQuantity=Math.max(1,detailQuantity-1);$("detailQuantity").textContent=detailQuantity;});$("detailPlus").addEventListener("click",()=>{const v=selectedVariant(),stock=v?v.stock:(detailProduct?.stock||0);if(detailQuantity<stock)detailQuantity++;$("detailQuantity").textContent=detailQuantity;});$("detailAdd").addEventListener("click",addSelectedToCart);document.querySelectorAll("[data-close-product]").forEach(x=>x.addEventListener("click",closeProduct));
const checkoutDialog=$("checkoutDialog");$("checkoutBtn").addEventListener("click",()=>{if(!cart.length)return alert("Your bag is empty.");if(currency==="USD")return alert("International checkout is not enabled yet. Please switch to ₱ PHP to complete payment.");if(cart.some(i=>{const p=getProduct(i.id),v=variants(p).find(x=>(x.color||"")===(i.color||"")&&(x.size||"")===(i.size||""));return !p||!p.price||(v?v.stock:p.stock)<i.quantity}))return alert("Please update your bag before checkout.");checkoutDialog.showModal();});
$("checkoutForm").addEventListener("submit",async e=>{e.preventDefault();if(!cart.length)return;const b=e.currentTarget.querySelector('button[type="submit"]'),original=b.textContent;b.disabled=true;b.textContent="CONNECTING TO PAYMONGO…";const form=new FormData(e.currentTarget),customer=Object.fromEntries(["name","email","phone","address"].map(k=>[k,String(form.get(k)||"").trim()]));try{const r=await fetch("/api/create-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart,customer})}),d=await r.json();if(!r.ok||!d.checkout_url)throw new Error(d.error||"Unable to create PayMongo checkout.");localStorage.setItem("kloksieLastOrderReference",d.reference_number||"");location.assign(d.checkout_url);}catch(err){alert(err.message||"Payment setup failed. Please try again.");b.disabled=false;b.textContent=original;}});$("year").textContent=new Date().getFullYear();renderCurrency();loadProducts();